<a href="https://colab.research.google.com/github/freamwork97/TIS/blob/main/%EB%84%98%ED%8C%8C%EC%9D%B4%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [12]:
a = [1,2,3,4]
print(a)
print(type(a))

[1, 2, 3, 4]
<class 'list'>


In [24]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
c = a+b
print(c)
print('-'*13)
c = a* b
print(c)
print('-'*13)
c = a- b
print(c)
print('-'*13)
c = a/ b
print(c)
print('-'*13)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
-------------
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
-------------
[[0 0 0]
 [0 0 0]
 [0 0 0]]
-------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-------------


In [48]:
import numpy as np

arr = np.array([1,2,3,4])
type(arr)

numpy.ndarray

In [49]:
import numpy as np

arr1 = np.array([1,2,3])  # int 자료형으로만 구성
arr2 = np.array([1,2,3.0]) # float 자료형 포함
arr3 = np.array([1,2,'3']) # str 자료형 포함

# dtype은 속성명
print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)

[1 2 3] int64
[1. 2. 3.] float64
['1' '2' '3'] <U21


In [92]:
arr1 = np.array([1,2,3]) # 1차원

arr2 = np.array([[1,2,3],
                 [4,5,6]]) # 2차원

arr3 = np.array([[[1,2,3],
                  [4,5,6],
                  [7,8,9]]]) # 3차원
                  
arr4 = np.array([[1],[2],[3]])

print(arr1)
print('-'*11)
print(arr2)
print('-'*11)
print(arr3)
print('-'*11)
print(arr4)
print('-'*11)

# 형태확인
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print(arr4.shape)
print('-'*11)

# 차원확인
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)
print('-'*11)


[1 2 3]
-----------
[[1 2 3]
 [4 5 6]]
-----------
[[[1 2]
  [4 5]
  [7 8]]]
-----------
[[1]
 [2]
 [3]]
-----------
(3,)
(2, 3)
(1, 3, 2)
(3, 1)
-----------
1
2
3
2
-----------


In [57]:
a = np.array([[10,20,30,40],[50,60,70,80]])
print(a)

[[10 20 30 40]
 [50 60 70 80]]


In [63]:
a = np.array([[[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]],
             [[11,12,13,14],
              [15,16,17,18],
              [19,20,21,22]]])
print(a)
len(a),len(a[0]), len(a[0][0])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


(2, 3, 4)

In [74]:
a = np.array([1,2,3,4,5,6,7])
print(a[2])
print(a[-1])
print(a[5])

3
7
6


In [80]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a[0][0])
print(a[1][2])
print(a[-1][-1])

[[1 2 3]
 [4 5 6]]
1
6
6


In [93]:
# 크기가 (4,)인 1차원 넘파이 배열 생성,
# 차원 및 형태 출력
a = np.array([1,2,3,4])
print(a)
print(a.shape)
print(a.ndim)


[1 2 3 4]
(4,)
1


In [117]:
# 크기가 (4,3)인 2차원 넘파이 배열 생성
# 차원 및 형태 출력
a = np.array([[1,2,3],
              [5,6,7],
              [9,10,11],
              [4,6,8]])
print(a)
print('-'*11)

print(a.shape)
print('-'*11)

print(a.ndim)
print('-'*11)

display(a)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [ 4  6  8]]
-----------
(4, 3)
-----------
2
-----------


array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [ 4,  6,  8]])

In [115]:
a = np.array([[0,1,2,3],
              [4,5,6,7]])
print(a)

print('-'*11)
print(a[0][:])

print('-'*11)
print(a[0][1:])

print('-'*11)
print(a[1,:2])

print('-'*11)
print(a[:,:2])

[[0 1 2 3]
 [4 5 6 7]]
-----------
[0 1 2 3]
-----------
[1 2 3]
-----------
[4 5]
-----------
[[0 1]
 [4 5]]


In [118]:
a = list(range(10))
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [130]:
print(np.arange(5,9))

[5 6 7 8]


In [137]:
arr1 = np.arange(5) # 0 ~ 5까지 1씩 증가
arr2 = np.arange(-1,4.5,1.5) # -1부터 4.5까지 1.5씩 증가
arr3 = np.arange(10,1,-1) # 10부터 1까지 -1씩 증가
arr4 = np.linspace(0,1,11) # 0부터 1까지 등간격의 11개의 요소 생성

display(arr1)
print('-'*40)

display(arr2)
print('-'*40)

display(arr3)
print('-'*40)

display(arr4)
print('-'*40)

array([0, 1, 2, 3, 4])

----------------------------------------


array([-1. ,  0.5,  2. ,  3.5])

----------------------------------------


array([10,  9,  8,  7,  6,  5,  4,  3,  2])

----------------------------------------


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

----------------------------------------


In [149]:
z1 = np.zeros(5) # 크기: 5
z2 = np.zeros((3,2)) # 크기: (3,2)
z3 = np.zeros(((3,3,3)))
z4 = np.zeros((2,2),dtype=bool) 
print(z1)
print(z1.ndim)
print(z1.shape)
print('-'*11)

print(z2)
print(z2.ndim)
print(z2.shape)
print('-'*11)

print(z3)
print(z3.ndim)
print(z3.shape)
print('-'*11)

print(z4)
print(z4.ndim)
print(z4.shape)

[0. 0. 0. 0. 0.]
1
(5,)
-----------
[[0. 0.]
 [0. 0.]
 [0. 0.]]
2
(3, 2)
-----------
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
3
(3, 3, 3)
-----------
[[False False]
 [False False]]
2
(2, 2)


In [157]:
n1 = np.ones((5,2), dtype='i')
n1

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [158]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [161]:
b = np.ones_like(a,dtype='f')
b

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [175]:
# 다음 배열(arr1)과 같은 크기를 가지며,
# 0과 1로만 채워진 두 개의 배열 생성
arr1 = np.array([[1,2,3],
                 [4,5,6]])
a = np.zeros_like(arr1)
b = np.ones_like(arr1)
print(a)
print('-'*10)
print(b)

[[0 0 0]
 [0 0 0]]
----------
[[1 1 1]
 [1 1 1]]


In [174]:
# 5 크기의 전부 0과 전부 1로 채워진 넘파이 배열을 생성
a = np.zeros(5)
b = np.ones(5)
print(a)
print('-'*15)
print(b)

[0. 0. 0. 0. 0.]
---------------
[1. 1. 1. 1. 1.]


In [169]:
# (3,4) 크기의 전부 0과 전부 1로 채워진 넘파이 배열 생성
# 차원과 크기 출력
a = np.zeros((3,4))
b = np.ones((3,4))
print(a.ndim)
print(a)
print('-'*15)
print(b.ndim)
print(b)

2
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
---------------
2
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [171]:
# 다음 배열(arr2)과 같은 크기를 가지며,
# 0과 1로만 채워진 두 개의 배열 생성
arr2 = np.array([[[1,2],
                  [3,4],
                  [5,6],
                  [7,8]]])
a = np.zeros_like(arr2)
b = np.ones_like(arr2)
print(a)
print('-'*10)
print(b)

[[[0 0]
  [0 0]
  [0 0]
  [0 0]]]
----------
[[[1 1]
  [1 1]
  [1 1]
  [1 1]]]


In [201]:

arr1 = np.random.random(5)
arr2 = np.random.random((2,2))

print(arr1)
print('-'*40)

print(arr2)

[0.11005192 0.22793516 0.42710779 0.81801477 0.86073058]
----------------------------------------
[[0.00695213 0.5107473 ]
 [0.417411   0.22210781]]


In [202]:
arr1 = np.random.normal(0,1,5)
arr2 = np.random.normal(10,3,(3,3))

print(arr1)
print('-'*40)
print(arr2)

[-0.34271452 -0.80227727 -0.16128571  0.40405086  1.8861859 ]
----------------------------------------
[[10.52373344 10.77265117  9.77666225]
 [ 4.24368635  9.92045837 10.18069063]
 [17.38972634  9.42291711 10.90464203]]


In [204]:
# 요소개수가 7
# 평균 0 
# 분산 1인 정규분포 난수 넘파이 배열 생성

a = np.random.normal(0,1,7)
print(a)

[-1.40185106  0.58685709  2.19045563 -0.99053633 -0.56629773  0.09965137
 -0.50347565]


In [217]:
# 다음 배열(arr)과 같은 크기의 평균 3
# 분산 2인 정규분포 난수 넘파이 배열 생성
# shape 활용

arr = np.zeros((3,2))
print(arr)
print('-'*20)

a = np.random.normal(3,2,(arr.shape))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
--------------------
[[2.1069701  4.71279759]
 [3.42818749 0.50852244]
 [3.34636185 3.77063476]]


In [224]:
a = np.arange(10)
idx = np.array([1,0,1,0,1,0,1,0,1,0],dtype=bool)

a[idx]

array([0, 2, 4, 6, 8])

In [225]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [226]:
a % 2 ==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [227]:
a[a%2==0]

array([0, 2, 4, 6, 8])