<a href="https://colab.research.google.com/github/freamwork97/TIS/blob/main/%EB%84%98%ED%8C%8C%EC%9D%B4%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [ ]:
a = [1,2,3,4]
print(a)
print(type(a))

[1, 2, 3, 4]
<class 'list'>


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
c = a+b
print(c)
print('-'*13)
c = a* b
print(c)
print('-'*13)
c = a- b
print(c)
print('-'*13)
c = a/ b
print(c)
print('-'*13)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
-------------
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
-------------
[[0 0 0]
 [0 0 0]
 [0 0 0]]
-------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-------------


In [ ]:
import numpy as np

arr = np.array([1,2,3,4])
type(arr)

numpy.ndarray

In [ ]:
import numpy as np

arr1 = np.array([1,2,3])  # int 자료형으로만 구성
arr2 = np.array([1,2,3.0]) # float 자료형 포함
arr3 = np.array([1,2,'3']) # str 자료형 포함

# dtype은 속성명
print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)

[1 2 3] int64
[1. 2. 3.] float64
['1' '2' '3'] <U21


In [ ]:
arr1 = np.array([1,2,3]) # 1차원

arr2 = np.array([[1,2,3],
                 [4,5,6]]) # 2차원

arr3 = np.array([[[1,2,3],
                  [4,5,6],
                  [7,8,9]]]) # 3차원
                  
arr4 = np.array([[1],[2],[3]])

print(arr1)
print('-'*11)
print(arr2)
print('-'*11)
print(arr3)
print('-'*11)
print(arr4)
print('-'*11)

# 형태확인
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print(arr4.shape)
print('-'*11)

# 차원확인
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)
print('-'*11)


[1 2 3]
-----------
[[1 2 3]
 [4 5 6]]
-----------
[[[1 2]
  [4 5]
  [7 8]]]
-----------
[[1]
 [2]
 [3]]
-----------
(3,)
(2, 3)
(1, 3, 2)
(3, 1)
-----------
1
2
3
2
-----------


In [ ]:
a = np.array([[10,20,30,40],[50,60,70,80]])
print(a)

[[10 20 30 40]
 [50 60 70 80]]


In [ ]:
a = np.array([[[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]],
             [[11,12,13,14],
              [15,16,17,18],
              [19,20,21,22]]])
print(a)
len(a),len(a[0]), len(a[0][0])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


(2, 3, 4)

In [ ]:
a = np.array([1,2,3,4,5,6,7])
print(a[2])
print(a[-1])
print(a[5])

3
7
6


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a[0][0])
print(a[1][2])
print(a[-1][-1])

[[1 2 3]
 [4 5 6]]
1
6
6


In [ ]:
# 크기가 (4,)인 1차원 넘파이 배열 생성,
# 차원 및 형태 출력
a = np.array([1,2,3,4])
print(a)
print(a.shape)
print(a.ndim)


[1 2 3 4]
(4,)
1


In [ ]:
# 크기가 (4,3)인 2차원 넘파이 배열 생성
# 차원 및 형태 출력
a = np.array([[1,2,3],
              [5,6,7],
              [9,10,11],
              [4,6,8]])
print(a)
print('-'*11)

print(a.shape)
print('-'*11)

print(a.ndim)
print('-'*11)

display(a)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [ 4  6  8]]
-----------
(4, 3)
-----------
2
-----------


array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [ 4,  6,  8]])

In [ ]:
a = np.array([[0,1,2,3],
              [4,5,6,7]])
print(a)

print('-'*11)
print(a[0][:])

print('-'*11)
print(a[0][1:])

print('-'*11)
print(a[1,:2])

print('-'*11)
print(a[:,:2])

[[0 1 2 3]
 [4 5 6 7]]
-----------
[0 1 2 3]
-----------
[1 2 3]
-----------
[4 5]
-----------
[[0 1]
 [4 5]]


In [ ]:
a = list(range(10))
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
print(np.arange(5,9))

[5 6 7 8]


In [ ]:
arr1 = np.arange(5) # 0 ~ 5까지 1씩 증가
arr2 = np.arange(-1,4.5,1.5) # -1부터 4.5까지 1.5씩 증가
arr3 = np.arange(10,1,-1) # 10부터 1까지 -1씩 증가
arr4 = np.linspace(0,1,11) # 0부터 1까지 등간격의 11개의 요소 생성

display(arr1)
print('-'*40)

display(arr2)
print('-'*40)

display(arr3)
print('-'*40)

display(arr4)
print('-'*40)

array([0, 1, 2, 3, 4])

----------------------------------------


array([-1. ,  0.5,  2. ,  3.5])

----------------------------------------


array([10,  9,  8,  7,  6,  5,  4,  3,  2])

----------------------------------------


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

----------------------------------------


In [ ]:
z1 = np.zeros(5) # 크기: 5
z2 = np.zeros((3,2)) # 크기: (3,2)
z3 = np.zeros(((3,3,3)))
z4 = np.zeros((2,2),dtype=bool) 
print(z1)
print(z1.ndim)
print(z1.shape)
print('-'*11)

print(z2)
print(z2.ndim)
print(z2.shape)
print('-'*11)

print(z3)
print(z3.ndim)
print(z3.shape)
print('-'*11)

print(z4)
print(z4.ndim)
print(z4.shape)

[0. 0. 0. 0. 0.]
1
(5,)
-----------
[[0. 0.]
 [0. 0.]
 [0. 0.]]
2
(3, 2)
-----------
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
3
(3, 3, 3)
-----------
[[False False]
 [False False]]
2
(2, 2)


In [ ]:
n1 = np.ones((5,2), dtype='i')
n1

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [ ]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b = np.ones_like(a,dtype='f')
b

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [ ]:
# 다음 배열(arr1)과 같은 크기를 가지며,
# 0과 1로만 채워진 두 개의 배열 생성
arr1 = np.array([[1,2,3],
                 [4,5,6]])
a = np.zeros_like(arr1)
b = np.ones_like(arr1)
print(a)
print('-'*10)
print(b)

[[0 0 0]
 [0 0 0]]
----------
[[1 1 1]
 [1 1 1]]


In [ ]:
# 5 크기의 전부 0과 전부 1로 채워진 넘파이 배열을 생성
a = np.zeros(5)
b = np.ones(5)
print(a)
print('-'*15)
print(b)

[0. 0. 0. 0. 0.]
---------------
[1. 1. 1. 1. 1.]


In [ ]:
# (3,4) 크기의 전부 0과 전부 1로 채워진 넘파이 배열 생성
# 차원과 크기 출력
a = np.zeros((3,4))
b = np.ones((3,4))
print(a.ndim)
print(a)
print('-'*15)
print(b.ndim)
print(b)

2
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
---------------
2
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# 다음 배열(arr2)과 같은 크기를 가지며,
# 0과 1로만 채워진 두 개의 배열 생성
arr2 = np.array([[[1,2],
                  [3,4],
                  [5,6],
                  [7,8]]])
a = np.zeros_like(arr2)
b = np.ones_like(arr2)
print(a)
print('-'*10)
print(b)

[[[0 0]
  [0 0]
  [0 0]
  [0 0]]]
----------
[[[1 1]
  [1 1]
  [1 1]
  [1 1]]]


In [ ]:

arr1 = np.random.random(5)
arr2 = np.random.random((2,2))

print(arr1)
print('-'*40)

print(arr2)

[0.11005192 0.22793516 0.42710779 0.81801477 0.86073058]
----------------------------------------
[[0.00695213 0.5107473 ]
 [0.417411   0.22210781]]


In [ ]:
arr1 = np.random.normal(0,1,5)
arr2 = np.random.normal(10,3,(3,3))

print(arr1)
print('-'*40)
print(arr2)

[-0.34271452 -0.80227727 -0.16128571  0.40405086  1.8861859 ]
----------------------------------------
[[10.52373344 10.77265117  9.77666225]
 [ 4.24368635  9.92045837 10.18069063]
 [17.38972634  9.42291711 10.90464203]]


In [ ]:
# 요소개수가 7
# 평균 0 
# 분산 1인 정규분포 난수 넘파이 배열 생성

a = np.random.normal(0,1,7)
print(a)

[-1.40185106  0.58685709  2.19045563 -0.99053633 -0.56629773  0.09965137
 -0.50347565]


In [ ]:
# 다음 배열(arr)과 같은 크기의 평균 3
# 분산 2인 정규분포 난수 넘파이 배열 생성
# shape 활용

arr = np.zeros((3,2))
print(arr)
print('-'*20)

a = np.random.normal(3,2,(arr.shape))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
--------------------
[[2.1069701  4.71279759]
 [3.42818749 0.50852244]
 [3.34636185 3.77063476]]


In [ ]:
a = np.arange(10)
idx = np.array([1,0,1,0,1,0,1,0,1,0],dtype=bool)
print(a)
print('-'*30)
print(idx)
print('-'*30)
a[idx]

[0 1 2 3 4 5 6 7 8 9]
------------------------------
[ True False  True False  True False  True False  True False]
------------------------------


array([0, 2, 4, 6, 8])

In [ ]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [ ]:
a % 2 ==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [ ]:
a[a%2==0]

array([0, 2, 4, 6, 8])

In [ ]:
# 다음 배열이 주어졌을 때,
# 크기 (3,8)인 2차원 배열 생성
arr = np.arange(24)
a = arr.reshape(3,8)
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [ ]:
# 위 배열을 (6,4)로 만들되,
# reshape() 메서드에서
# -1을 첫 번째로 인자로 활용
a = arr.reshape(-1,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# 난수 시드 설정
a = np.random.seed(42)
np.random.rand(10)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [ ]:
np.random.rand(5)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [ ]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [ ]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [ ]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [ ]:
# np.random.shuffle()
x = np.arange(10)
np.random.shuffle(x)
x

array([0, 5, 2, 6, 3, 7, 4, 1, 8, 9])

In [ ]:
np.random.choice(x,size=4,replace=True)

array([2, 1, 7, 2])

In [ ]:
# '오늘 뭐 먹지?' 라는 모바일 앱을 만들 때
menu = ['라면','스파게티','된장찌게','파전']
menu_arr = np.array(menu)

for i in range(20):
  today_recommended_menu = np.random.choice(menu_arr,size=1,replace =True, p=[0.1, 0.1, 0.1, 0.7])
  print(today_recommended_menu)


['파전']
['된장찌게']
['파전']
['파전']
['파전']
['라면']
['파전']
['파전']
['파전']
['파전']
['파전']
['파전']
['파전']
['파전']
['라면']
['파전']
['파전']
['된장찌게']
['스파게티']
['파전']


In [ ]:
# randn: 표준 정규 분포 (평균 0, 분산 1)
# randint: 균일 분포의 정수 난수
# 로또 번호 생성기 (1~45) 숫자 7개의 임의 숫자 추출
np.random.randint(45,size=7)

array([21, 36, 23,  6, 24, 24, 12])

In [ ]:
np.random.seed(0)
np.random.randint(45,size=7)

array([44,  0,  3,  3, 39,  9, 19])

In [ ]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2,3],[4,5,6]])

print(arr1.reshape(3,2))
print('-'*10)
print(arr2.reshape(-1,2))
print('-'*10)
print(arr1.reshape(-1,1))

[[1 2]
 [3 4]
 [5 6]]
----------
[[1 2]
 [3 4]
 [5 6]]
----------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
arr1 = np.zeros((4,3))
print(arr1)
print('-'*20)

arr2 = arr1.reshape(2,6)
print(arr2)
print('-'*20)

arr3 = arr1.reshape(2,3,2)
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
--------------------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
--------------------
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
a = np.arange(12)
print(a)
print('-'*20)

b = a.reshape(3,4)
print(b)
print('-'*20)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
--------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------


In [ ]:
# 다음 배열이 주어졌을 때
# 이 배열과 구성 요소가 같고 크기만 (3,8)로 2차원 배열 생성
arr = np.arange(24)
print(arr)
print('-'*40)
a= arr.reshape(3,8)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
----------------------------------------
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [ ]:
# 위 배열을 (6,4)로 만들되,
# reshape() 메서드에서 -1을 첫 번째 인자로 활용
a = arr.reshape(-1,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
# 위 배열을 (3,4,2)크기로
# 두번째 인자를 -1로 활용
# 원하는 형태로 잘 변하는지 shape속성 활용
a = arr.reshape(3,-1,2)
print(a)
print('-'*15)
print(a.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
---------------
(3, 4, 2)


In [ ]:
np.random.seed(0)
a = np.random.randint(30,size=10)
b=a.reshape(5,2)
print(b)
print('-'*15)
c = np.random.randint(30,size=10)
d=c.reshape(5,2)
print(d)
print('-'*15)
e=b+d
print(e)

[[12 15]
 [21  0]
 [ 3 27]
 [ 3  7]
 [ 9 19]]
---------------
[[21 18]
 [ 4 23]
 [ 6 24]
 [24 12]
 [26  1]]
---------------
[[33 33]
 [25 23]
 [ 9 51]
 [27 19]
 [35 20]]


In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
a+b


array([5, 7, 9])

In [ ]:
x1 = np.random.rand(10**6) # 100만개 난수로 구성된 배열 생성
x2 = np.random.rand(10**6)


In [ ]:
%%timeit
s = x1 + x2 # ms = 1/1000 second


1.9 ms ± 54.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
%%timeit
s = []

for e1, e2 in zip(x1,x2):
  s.append(e1+ e2)

372 ms ± 122 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
x = np.arange(4)
y = np.linspace(1,10,4)
print('x     =',x)
print('y     =',y)
print('x + 5 =',x + 5)
print('x + y =',x + y)
print('x - 5 =',x - 5)
print('x - y =',x - y)
print('x * 2 =',x * 2)
print('x * y =',x * y)
print('x / 2 =',x / 2)
print('-x    =',-x)
print('x ** 2 =',x ** 2)
print('x % 2 =',x % 2)

x     = [0 1 2 3]
y     = [ 1.  4.  7. 10.]
x + 5 = [5 6 7 8]
x + y = [ 1.  5.  9. 13.]
x - 5 = [-5 -4 -3 -2]
x - y = [-1. -3. -5. -7.]
x * 2 = [0 2 4 6]
x * y = [ 0.  4. 14. 30.]
x / 2 = [0.  0.5 1.  1.5]
-x    = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2 = [0 1 0 1]


In [ ]:
# 연습문제
# 1~100까지 1씩 증가하는 원소(요소)로
# 구성된 넘파이 배열
# 각각의 요소에 3제곱한 새로운 배열 생성
a = np.arange(1,101,1)
print(a)
print('-'*50)
b = a**3
print(b)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
--------------------------------------------------
[      1       8      27      64     125     216     343     512     729
    1000    1331    1728    2197    2744    3375    4096    4913    5832
    6859    8000    9261   10648   12167   13824   15625   17576   19683
   21952   24389   27000   29791   32768   35937   39304   42875   46656
   50653   54872   59319   64000   68921   74088   79507   85184   91125
   97336  103823  110592  117649  125000  132651  140608  148877  157464
  166375  175616  185193  195112  205379  216000  226981  238328  250047
  262144  274625  287496  30076

In [ ]:
# 각각의 요소를 제곱근을 취한 새로운 배열을 생성
c=np.sqrt(a)
print(c)

[ 1.          1.41421356  1.73205081  2.          2.23606798  2.44948974
  2.64575131  2.82842712  3.          3.16227766  3.31662479  3.46410162
  3.60555128  3.74165739  3.87298335  4.          4.12310563  4.24264069
  4.35889894  4.47213595  4.58257569  4.69041576  4.79583152  4.89897949
  5.          5.09901951  5.19615242  5.29150262  5.38516481  5.47722558
  5.56776436  5.65685425  5.74456265  5.83095189  5.91607978  6.
  6.08276253  6.164414    6.244998    6.32455532  6.40312424  6.4807407
  6.55743852  6.63324958  6.70820393  6.78232998  6.8556546   6.92820323
  7.          7.07106781  7.14142843  7.21110255  7.28010989  7.34846923
  7.41619849  7.48331477  7.54983444  7.61577311  7.68114575  7.74596669
  7.81024968  7.87400787  7.93725393  8.          8.06225775  8.1240384
  8.18535277  8.24621125  8.30662386  8.36660027  8.42614977  8.48528137
  8.54400375  8.60232527  8.66025404  8.71779789  8.77496439  8.83176087
  8.88819442  8.94427191  9.          9.05538514  9.11043358 

In [ ]:
# 각각의 요소에 10을 더한 새로운 배열 생성
d = a+10
print(d)

[ 11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28
  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46
  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64
  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82
  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100
 101 102 103 104 105 106 107 108 109 110]


In [ ]:
# 절대값
x = np.array([-2,-1,0,1,2])
print('abs(x)', np.abs(x))

abs(x) [2 1 0 1 2]


In [ ]:
# 연습
# 각각의 원소에 3을 곱하고 1을 뺀 함수를 구현하여 적용
arr = np.arange(10)

def aa(a):
  return a*3-1

aa(arr)

array([-1,  2,  5,  8, 11, 14, 17, 20, 23, 26])

In [ ]:
x = np.array([1,2,3])
y = np.array([1,3,-2])
print('x == y:',x == y)
print('x > y:', x > y)
print('x >= 1:',x >= 1)
print('x >= 2:',x >= 2)

x == y: [ True False False]
x > y: [False False  True]
x >= 1: [ True  True  True]
x >= 2: [False  True  True]


In [ ]:
print(sum(x>=2))

2


In [ ]:
# 다음 배열에서 짝수인 요소의 개수를 출력
arr = np.arange(45)
print(sum(arr % 2 == 0))

23


In [ ]:
arr = np.arange(45)
cond = arr % 2 == 0
print(sum(cond))

23


In [ ]:
arr + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [ ]:
x = np.arange(4)
print(x +4)

[4 5 6 7]


In [ ]:
a = np.array([[1,2],[3,4]]) # (2,2) 2차원 배열, 행렬
b = np.array([-1,-2]) # (1, ) 1차원 배열, 벡터
print(a,)
print('-'*10)
print(b)
print('-'*10)
print(a+b)

[[1 2]
 [3 4]]
----------
[-1 -2]
----------
[[0 0]
 [2 2]]


In [ ]:
import numpy as np
x = np.arange(15).reshape(5,3)
display(x)
print('-'*25)
print(x)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

-------------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
print(np.sum(x))
print(x.sum())

105
105


In [ ]:
print(np.arange(15).reshape(5,3).sum())

105


In [ ]:
print(np.sum(x,axis=1))
print(x.sum(axis=0))

[ 3 12 21 30 39]
[30 35 40]


In [14]:
import numpy as np
x = np.arange(15).reshape(5,3)
print(x)
print('-'*20)

display(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
--------------------


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [11]:
print(x.sum())
print(x.min())
print(x.max())
print(x.mean())
print(x.std())
print(x.var())

105
0
14
7.0
4.320493798938574
18.666666666666668


In [17]:
print(np.sum(x))
print(x.sum())

105
105


In [27]:
print(np.sum(x,axis=1))
print('-'*20)
print(np.sum(x,axis=0))

[ 3 12 21 30 39]
--------------------
[30 35 40]


In [28]:
print(x.sum(axis=1))
print('-'*20)
print(x.sum(axis=0))

[ 3 12 21 30 39]
--------------------
[30 35 40]


In [33]:
print(x.max(axis=1))
print('-'*20)
print(x.max(axis=0))

[ 2  5  8 11 14]
--------------------
[12 13 14]


In [35]:
# 넘파이 배열로 전환, 평균, 중앙값
a_list = [1,3,5,7,100]
arr = np.array(a_list)
print(arr)

[  1   3   5   7 100]


In [36]:
np.mean(arr)

23.2

In [38]:
np.median(arr)

5.0

In [39]:
np.sum(arr)

116

In [40]:
np.max(arr)

100

In [41]:
np.min(arr)

1

In [47]:
np.unique(arr)

array([  1,   3,   5,   7, 100])

In [62]:
# quantile

arr = np.arange(1, 101)
np.quantile(arr, 0.25)

25.75

In [67]:
# 연습
# 다음 배열의 unique함수를 적용
a_list = np.array([1,3,5,7,9,3,5,100])
print(np.unique(a_list))
print('-'*20)
print(a_list)

[  1   3   5   7   9 100]
--------------------
[  1   3   5   7   9   3   5 100]


In [68]:
# f-string 버전
print("="*20, 'f-string 버전', "="*20)

print(f"열별 합계: {np.sum(x, axis = 0)}")
print(f"전체 합계: {np.sum(x)}")
print(f"행별 최솟값: {x.min(axis = 1)}")
print(f"행 방향 최솟값: {x.min(axis = 0)}")
print(f"전체 최댓값: {x.max()}")
print(f"열별 표준편차: {np.std(x, axis = 0)}")
print(f"전체 중위수: {np.median(x)}")
print(f"전체 상위 20%: {np.quantile(x, 0.2)}")
print(f"유니크한 값 목록: {np.unique(x)}")


==================== f-string 버전 ====================
열별 합계: [30 35 40]
전체 합계: 105
행별 최솟값: [ 0  3  6  9 12]
행 방향 최솟값: [0 1 2]
전체 최댓값: 14
열별 표준편차: [4.24264069 4.24264069 4.24264069]
전체 중위수: 7.0
전체 상위 20%: 2.8000000000000003
유니크한 값 목록: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [73]:
# 연습
# 다음 리스트 자료가 있다
# 넘파이 배열로 전환, 다음 통계를 구하라
# 평균, 표준편차, 중앙값, 최대값, 최소값
a_list =list(range(30))
print(a_list)
print('-'*20)
a = np.array(a_list)
print(a)
print('-'*20)
print('평균 :',np.mean(a))
print('표준편차 :',np.std(a))
print('중앙값 :',np.median(a))
print('최대값 :',np.max(a))
print('최소값 :',np.min(a))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
--------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
--------------------
평균 : 14.5
표준편차 : 8.65544144839919
중앙값 : 14.5
최대값 : 29
최소값 : 0


In [78]:
# 연습문제2
# 위 리스트를 (5,6) 크기의 넘파이 배열로 전환하고, 열별, 행별 통계량을 구하시오.
b= a.reshape(5,6)
print(b)
print('-'*20)

print('열별 평균 :',np.mean(b,axis=0))
print('행별 평균 :',np.mean(b,axis=1))
print('-'*20)

print('열별 표준편차 :',np.std(b,axis=0))
print('행별 표준편차 :',np.std(b,axis=1))
print('-'*20)

print('열별 중앙값 :',np.median(b, axis=0))
print('행별 중앙값 :',np.median(b, axis=1))
print('-'*20)

print('열별 최대값 :',np.max(b, axis=0))
print('행별 최대값 :',np.max(b, axis=1))
print('-'*20)

print('열별 최소값 :',np.min(b, axis=0))
print('행별 최소값 :',np.min(b, axis=1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
--------------------
열별 평균 : [12. 13. 14. 15. 16. 17.]
행별 평균 : [ 2.5  8.5 14.5 20.5 26.5]
--------------------
열별 표준편차 : [8.48528137 8.48528137 8.48528137 8.48528137 8.48528137 8.48528137]
행별 표준편차 : [1.70782513 1.70782513 1.70782513 1.70782513 1.70782513]
--------------------
열별 중앙값 : [12. 13. 14. 15. 16. 17.]
행별 중앙값 : [ 2.5  8.5 14.5 20.5 26.5]
--------------------
열별 최대값 : [24 25 26 27 28 29]
행별 최대값 : [ 5 11 17 23 29]
--------------------
열별 최소값 : [0 1 2 3 4 5]
행별 최소값 : [ 0  6 12 18 24]


In [86]:
print(f'열별 평균 : {np.mean(b,axis=0)}')
print(f'행별 평균 : {np.mean(b,axis=1)}')
print('-'*20)

print(f'열별 표준편차 : {np.std(b, axis=0)}')
print(f'행별 표준편차 : {np.std(b, axis=1)}')
print('-'*20)

print(f'열별 중앙값 : {np.median(b, axis=0)}')
print(f'행별 중앙값 : {np.median(b, axis=1)}')
print('-'*20)

print(f'열별 최대값 : {np.max(b, axis=0)}')
print(f'행별 최대값 : {np.max(b, axis=1)}')
print('-'*20)

print(f'열별 최소값 : {np.min(b, axis=0)}')
print(f'행별 최소값 : {np.min(b, axis=1)}')

열별 평균 : [12. 13. 14. 15. 16. 17.]
행별 평균 : [ 2.5  8.5 14.5 20.5 26.5]
--------------------
열별 표준편차 : [8.48528137 8.48528137 8.48528137 8.48528137 8.48528137 8.48528137]
행별 표준편차 : [1.70782513 1.70782513 1.70782513 1.70782513 1.70782513]
--------------------
열별 중앙값 : [12. 13. 14. 15. 16. 17.]
행별 중앙값 : [ 2.5  8.5 14.5 20.5 26.5]
--------------------
열별 최대값 : [24 25 26 27 28 29]
행별 최대값 : [ 5 11 17 23 29]
--------------------
열별 최소값 : [0 1 2 3 4 5]
행별 최소값 : [ 0  6 12 18 24]


In [143]:
a= np.arange(30)
b=a.reshape(5,6)
print(b)
print('-'*20)
print(b[1:3,0:2])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
--------------------
[[ 6  7]
 [12 13]]


In [149]:
x = [[1,2],[3,4]]
print('리스트 자료형')
print(x)
print(x[0])
print('-'*20)

a = np.array(x)
print('넘파이 배열')
print(a)
print(a[0][1])
print('-'*20)


리스트 자료형
[[1, 2], [3, 4]]
[1, 2]
--------------------
넘파이 배열
[[1 2]
 [3 4]]
2
--------------------


In [163]:
a = [[1,2,3,4,5,6],[3,4,5,6,7,8]]
b = np.array(a)
print(b)
print('-'*20)
print(b[0][3:])
print(b[1][:3])
print(b[0][2])
print(b[1][4])

[[1 2 3 4 5 6]
 [3 4 5 6 7 8]]
--------------------
[4 5 6]
[3 4 5]
3
7


In [195]:
a = [[1,2,3,4,5,6],[3,4,5,6,7,8],[11,22,33,44,55,66]]
b = np.array(a)
print(b)
print('-'*20)
print(b[0:,3:])
print('-'*20)
print(b[1:,2:5])
print('-'*20)
print(b[[0,2]])
print('-'*20)
print(b[:,1:2])

[[ 1  2  3  4  5  6]
 [ 3  4  5  6  7  8]
 [11 22 33 44 55 66]]
--------------------
[[ 4  5  6]
 [ 6  7  8]
 [44 55 66]]
--------------------
[[ 5  6  7]
 [33 44 55]]
--------------------
[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]
--------------------
[[ 2]
 [ 4]
 [22]]


In [207]:
# 다음 넘파이 배열 대상으로
# 요구하는 행과 열을 추출

arr = np.arange(30).reshape(5,6)
print(arr)
print('-'*20)

# 1번째 행 추출
print(arr[1])
print('-'*20)
# 0번째 열 추출
print(arr[:,0])
print('-'*20)
# 1번째~3번째 행, 0번째 ~ 2번째 열 추출
print(arr[1:4,0:3])
print('-'*20)
# 2번째 행, 3번째~5번째 열 추출
print(arr[2,3:])
print('-'*20)
# 2번째~4번째 행, 3번째 열 추출
print(arr[2:,3])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
--------------------
[ 6  7  8  9 10 11]
--------------------
[ 0  6 12 18 24]
--------------------
[[ 6  7  8]
 [12 13 14]
 [18 19 20]]
--------------------
[15 16 17]
--------------------
[15 21 27]


In [222]:
# 오늘 메뉴 넘파이 인덱싱 및 슬라이싱 활용 추출
weekly_menu = [['백미밥/잡곡밥', '육개장', '두부양념조림', '할라마요함박스테이크', '시금치고추장무침', '콩나물볶음/포기김치'],
               ['백미밥/잡곡밥', '김치수제비', '부대햄야채볶음', '야채계란찜', '수제양념깻잎지', '건파래볶음/포기김치'] ,
               ['백미밥/잡곡밥','배추된장국','닭볶음탕(김치)','사각어묵야채볶음','브로콜리,물미역&초장','상추겉절이/포기김치'],
               ['백미밥/잡곡밥', '돈육김치찌개', '김치스파게티', '청파래생선까스 & 어니언소스','느타리유부무침','미역줄기볶음/포기김치'],
               ['백미밥/잡곡밥', '콩나물김치국', '간장불고기', '야채비빔만두', '도토리묵&달래장', '부추겉절이']]
# 넘파이 배열로 변환
a = np.array(weekly_menu)
print(a)
print('-'*30)
print(a.shape)

[['백미밥/잡곡밥' '육개장' '두부양념조림' '할라마요함박스테이크' '시금치고추장무침' '콩나물볶음/포기김치']
 ['백미밥/잡곡밥' '김치수제비' '부대햄야채볶음' '야채계란찜' '수제양념깻잎지' '건파래볶음/포기김치']
 ['백미밥/잡곡밥' '배추된장국' '닭볶음탕(김치)' '사각어묵야채볶음' '브로콜리,물미역&초장' '상추겉절이/포기김치']
 ['백미밥/잡곡밥' '돈육김치찌개' '김치스파게티' '청파래생선까스 & 어니언소스' '느타리유부무침' '미역줄기볶음/포기김치']
 ['백미밥/잡곡밥' '콩나물김치국' '간장불고기' '야채비빔만두' '도토리묵&달래장' '부추겉절이']]
------------------------------
(5, 6)


In [243]:
# 인덱싱이나 슬라이싱 이용하여 오늘(수요일)의 메뉴 출력
print(f'수요일 메뉴 : {a[2]}')
# print(f'수요일 메뉴 : {a[2,:]}')
# 인덱싱이나 슬라이싱 이용하여 오늘(수요일)의 국을 출력
print(f'수요일 국 : {a[2,1]}')
# 인덱싱이나 슬라이싱 이용하여 이번주 국을 모두 출력
print(f'이번주 국 : {a[:,1]}')


수요일 메뉴 : ['백미밥/잡곡밥' '배추된장국' '닭볶음탕(김치)' '사각어묵야채볶음' '브로콜리,물미역&초장' '상추겉절이/포기김치']
수요일 국 : 배추된장국
이번주 국 : ['육개장' '김치수제비' '배추된장국' '돈육김치찌개' '콩나물김치국']


In [250]:
# 전치(transpose): 행과 열을 바꿈
weekly_menu = [['백미밥/잡곡밥', '육개장', '두부양념조림', '할라마요함박스테이크', '시금치고추장무침', '콩나물볶음/포기김치'],
               ['백미밥/잡곡밥', '김치수제비', '부대햄야채볶음', '야채계란찜', '수제양념깻잎지', '건파래볶음/포기김치'] ,
               ['백미밥/잡곡밥','배추된장국','닭볶음탕(김치)','사각어묵야채볶음','브로콜리,물미역&초장','상추겉절이/포기김치'],
               ['백미밥/잡곡밥', '돈육김치찌개', '김치스파게티', '청파래생선까스 & 어니언소스','느타리유부무침','미역줄기볶음/포기김치'],
               ['백미밥/잡곡밥', '콩나물김치국', '간장불고기', '야채비빔만두', '도토리묵&달래장', '부추겉절이']]

a = np.transpose(weekly_menu)
print(a.shape)
print(a)

(6, 5)
[['백미밥/잡곡밥' '백미밥/잡곡밥' '백미밥/잡곡밥' '백미밥/잡곡밥' '백미밥/잡곡밥']
 ['육개장' '김치수제비' '배추된장국' '돈육김치찌개' '콩나물김치국']
 ['두부양념조림' '부대햄야채볶음' '닭볶음탕(김치)' '김치스파게티' '간장불고기']
 ['할라마요함박스테이크' '야채계란찜' '사각어묵야채볶음' '청파래생선까스 & 어니언소스' '야채비빔만두']
 ['시금치고추장무침' '수제양념깻잎지' '브로콜리,물미역&초장' '느타리유부무침' '도토리묵&달래장']
 ['콩나물볶음/포기김치' '건파래볶음/포기김치' '상추겉절이/포기김치' '미역줄기볶음/포기김치' '부추겉절이']]


In [255]:
x = np.array([1,2,3,4,5])
b = [True,False,True,True,False]
print(x[b])
print(x[[True,False,True,True,False]])

[1 3 4]
[1 3 4]


In [256]:
x = np.array([1,2,3,4,5])
cond = x>=3
print(cond)
print(x[cond])

[False False  True  True  True]
[3 4 5]


In [258]:
print(x[x>=3])

[3 4 5]


In [266]:
# 다음 배열에서 5보다 작은 요소들만 추출
a = np.arange(10)
print(a[a<5])
print('-'*12)
# 위 배열에서 짝수인 요소들만 추출
print(a[a % 2 == 0])

[0 1 2 3 4]
------------
[0 2 4 6 8]


In [283]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 이 배열에서 3의 배수를 찾아라.
print(x[x%3 == 0])
print('-'*12)

# 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
print(x[x%4==1])
print('-'*12)

# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
print(x[(x%3 == 0) & (x%4 == 1)])

[ 3  6  9 12 15 18]
------------
[ 1  5  9 13 17]
------------
[9]
